import './globals.css'
import { Inter } from 'next/font/google'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1>This is Header</h1>
        </header>
        {children}
        <footer>
          <p>This is Footer</p>
        </footer>
      </body>
    </html>
  )
}
