import React from 'react';
import SidebarComponent from '../components/Shared/Sidebar';

export const metadata = {
    title: 'NextJS Dashboard Layout',
    description: 'Generated by create next app NextJS Dashboard Layout',
}

const DashboardLayout = ({ children }) => {
    return (
        <div className=' flex'>
            <SidebarComponent></SidebarComponent>
            <div className=' w-full'>
                {children}
            </div>
        </div>
    );
};

export default DashboardLayout;